name: Build and Release TNS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Install build prerequisites.
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Use Luna to make.
        run: |
          git clone --depth 1 https://github.com/ndless-nspire/Luna
          cd Luna
          make

      - name: Extract version from abaco.py
        id: version
        run: |
          VERSION=$(grep -E '^Version:' abaco.py | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build TNS file.
        run: |
          ./Luna/luna abaco.py absco-${{ steps.version.outputs.version }}.tns

      - name: Create release and upload asset.
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: "abaco v${{ steps.version.outputs.version }}"
          body: "TNS file built from abaco.py"
          files: abaco-${{ steps.version.outputs.version }}.tns
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
